baseURL: "https://raw-tech.co.uk/"
title: "RAW-TECH"
theme: "PaperMod"
defaultContentLanguage: en
enableRobotsTXT: true
buildDrafts: false

pagination:
  pagerSize: 10

taxonomies:
  tag: "tags"
  category: "categories"

params:
  description: "RAW-TECH"
  author: "Ryan Witts"
  env: production
  images:
    - "/images/Logo.png"
  defaultSection: recipes
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true

  assets:
    favicon: "/favicon.ico"

  showRecent: true
  homePostsSection: "posts"
  recentPostsLimit: 5

  ShowPostCover: true
  ShowPostCoverInList: true
  ShowPostCoverInSingle: true
  ShowShareButtons: false
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  ShowWordCount: true

markup:
  goldmark:
    renderer:
      unsafe: true
      
  cover:
    responsiveImages: true
    hidden: false
    linkFullImages: true

  assets:
    disableFingerprinting: true
  editPost:
    showCodeCopyButtons: true

  socialIcons:
    - name: github
      url: "https://github.com/Kame-Ry"
    - name: linkedin
      url: "https://www.linkedin.com/in/ryan-witts-72993a181/"

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 2
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 3
    - identifier: recipes
      name: Cookbook
      url: /recipes/
      weight: 4
